name: Web API Automation Testing Workflow

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:

permissions: 
  contents: read
  pages: write

jobs:
 Build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    
    - name: Set up JDK 23
      uses: actions/setup-java@v4.0.0
      with:
        java-version: '23'
        distribution: 'temurin'

    - name: Setup Firefox
      uses: browser-actions/setup-firefox@v1.5.4
      with:
          firefox-version: latest
          firefox-option: '--headless'
  
    - name: Setup gradlew
      run: chmod +x gradlew

    - name: Execute Test
      run: ./gradlew clean test

    - name: Archive test results
      uses: actions/upload-artifact@v4.3.0
      if: always ()
      with:
        name: cucumber reports
        path: target/cucumber-reports.html
