name: Web API Automation Testing Workflow

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  Web API AutoTest:

    runs-on: macos-latest

    steps:
    - uses: actions/checkout@v4
    
    - name: Set up JDK 17
      uses: actions/setup-java@v4
      with:
        java-version: '17'
        distribution: 'temurin'

    - name: Setup Firefox
  uses: browser-actions/setup-firefox@v1.5.4

   - name: gradlew setup
   run: Chmod +x gradlew

   - name: Execute test
   run: ./gradlew cucumber
   

  
  

