name: Web API Automation Testing Workflow

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:

permision: 
  contents: read
  pages: write
  id-token: write

jobs:
  Web API AutoTest:

    runs-on: ubuntu-lates

    steps:
    - uses: actions/checkout@v4
    
    - name: Set up JDK 23
      uses: actions/setup-java@v4
      with:
        java-version: '23'
        distribution: 'temurin'

    - name: Setup Firefox
  # You may pin to the exact commit or the version.
  # uses: browser-actions/setup-firefox@634a60ccd6599686158cf5a570481b4cd30455a2
  uses: browser-actions/setup-firefox@v1.5.4
  with:
    # The Firefox version to install and use. Examples: 84.0, 84.0.1, latest-esr
    firefox-version: # optional
          

      - name: Build with Gradle
          run:chmod +x gradlew
          ./gradlew build

      - name: Run Test
    run: ./gradlew clean test

        - name: Archive test results
      uses: action/upload-artifact@v4.3.0
      if: always()
      with:
        name: cucumber reports
        path: target/cucumber-reports.html
   

  
  

