name: Web API Automation Testing Workflow

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:


jobs:
 Build:
    runs-on: macos-lates

    steps:
    - uses: actions/checkout@v4
    
    - name: Set up JDK 23
      uses: actions/setup-java@v3
      with:
        java-version: '23'
        distribution: 'temurin'

    - name: Setup Chrome
      uses: browser-actions/setup-chrome@v0.0.0
  
    - name: Setup gradlew
      run: chmod +x gradlew

    - name: Execute Test
      run: ./gradlew clean test

    #   - name: Run Test
    # run: ./gradlew clean test

    # - name: Archive test results
    #   uses: action/upload-artifact@v4.3.0
    #   if: always()
    #   with:
    #     name: cucumber reports
    #     path: target/cucumber-reports.html
   

  
  

